### ISSUE TITLE
Pwochen dat yon kou ak nonb plas ki rete pou pwochen dat kou a

### ISSUE THREAD

**Issue by Chamane** [esih-makerlab/makerlab#9]
Mwen bezwen bay pwochen dat yon kou ap fèt kote gen plas ki rete pou li epi map bezwen di konbyen plas. Mete sa kòm yon fonksyon sou modèl yo, kote li ranvoye pwochen dat kote gen plas pou yon kou

**Comment by undisplay** [comment]
Mw tavay sou li li basic kounya me map augmantel
